repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
    - id: pytest-check
      name: pytest-check
      entry: pytest test/unit_tests.py
      language: system
      pass_filenames: false
      always_run: true