name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Set build id'
      id: build_id
      # add a step output `steps.build_id.outputs.id` as the unique id
      run: echo "::set-output name=id::$(date +%s)"
    - name: Build the Docker image
      run: |
        docker build -t vincyzed/oxygencs-grp1-eq10:latest -t louishorlaville/log680_eq10_oxygen:${{ steps.build_id.outputs.id }} .
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 'Public image to Docker Hub'
      run: |
        docker push louishorlaville/log680_eq10_oxygen:${{ steps.build_id.outputs.id }}
        docker push louishorlaville/log680_eq10_oxygen:latest
