name: Kubernetes Deploy

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: [main]
    types: 
      - completed

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete old pod
        uses: actions-hub/kubectl@master
        with:
          args: delete -f k8s/deployment.yaml
      - name: Deploy App
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k8s/
